version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: my-db
    ports:
      - 5555:5432
    volumes:
      - my-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  my-db:
    driver: local
